/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BedWars;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Alexandre VUCEMILOVIC
 */



public class FenetreDeDemarrage extends javax.swing.JFrame {

    public Jeu jeu = new Jeu("test", 1);
    
    public int getEquipe(){
        String texte = boutonEquipe.getText();
        
        if (texte.equals("Equipe 1")){
            return(1);
        }
        return(2);
    }
    
    
    public FenetreDeDemarrage() throws SQLException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lancerLaPartie = new javax.swing.JButton();
        pseudo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelPseudo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelEquipe = new javax.swing.JLabel();
        boutonEquipe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lancerLaPartie.setBackground(new java.awt.Color(255, 0, 0));
        lancerLaPartie.setText("Il faut un pseudo !");
        lancerLaPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lancerLaPartieActionPerformed(evt);
            }
        });

        pseudo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pseudo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pseudoKeyReleased(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pseudo");

        jLabelPseudo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPseudo.setText("Pseudo");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Equipe");

        jLabelEquipe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEquipe.setText("Equipe");

        boutonEquipe.setBackground(new java.awt.Color(0, 255, 0));
        boutonEquipe.setText("Equipe 1");
        boutonEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonEquipeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boutonEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lancerLaPartie, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(lancerLaPartie, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lancerLaPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lancerLaPartieActionPerformed
        if(!pseudo.getText().equals("")){
                        
            String pseudoTemp = pseudo.getText();
            int equipeTemp = this.getEquipe();
                    
            FenetreDeJeuGUI fenetre = null;
            try {
                fenetre = new FenetreDeJeuGUI(this.jeu, pseudoTemp, equipeTemp);
            } catch (SQLException ex) {
                Logger.getLogger(FenetreDeDemarrage.class.getName()).log(Level.SEVERE, null, ex);
            }
            fenetre.setVisible(true);
        
        } else {
            
        }
    }//GEN-LAST:event_lancerLaPartieActionPerformed

    private void pseudoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pseudoKeyReleased
        this.jeu.joueur.setPseudo(pseudo.getText());
        jLabelPseudo.setText(this.jeu.joueur.getPseudo());
        
        if(!pseudo.getText().equals("")){
            lancerLaPartie.setBackground(Color.GREEN);
            lancerLaPartie.setText("Lancer la partie");
        } else {
            lancerLaPartie.setBackground(Color.RED);
            lancerLaPartie.setText("Il faut un pseudo !");
        }
    }//GEN-LAST:event_pseudoKeyReleased

    private void boutonEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonEquipeActionPerformed
        if (boutonEquipe.getText().equals("Equipe 1")){
            boutonEquipe.setText("Equipe 2");
            boutonEquipe.setBackground(Color.RED);
        } else {
            boutonEquipe.setText("Equipe 1");
            boutonEquipe.setBackground(Color.GREEN);    
        }
    }//GEN-LAST:event_boutonEquipeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDeDemarrage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDeDemarrage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDeDemarrage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDeDemarrage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FenetreDeDemarrage().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FenetreDeDemarrage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonEquipe;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelEquipe;
    private javax.swing.JLabel jLabelPseudo;
    private javax.swing.JButton lancerLaPartie;
    private javax.swing.JTextField pseudo;
    // End of variables declaration//GEN-END:variables
}
